Fixing git action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -23,6 +23,13 @@ jobs:
           distribution: 'temurin'
           cache: 'gradle'
 
+      - name: Verify Gradle Wrapper
+        run: |
+          if [ ! -f ./apk/gradlew/gradle-wrapper.jar ]; then
+            echo "Error: gradle-wrapper.jar not found in apk directory!"
+            exit 1
+          fi
+
       - name: Grant execute permission for gradlew
         run: chmod +x ./apk/gradlew
 
